apiVersion: v1
kind: Service
metadata:
  name: myportfolio
spec:
  selector:
    app: myportfolio
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myportfolio
  type: ClusterIP